version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  release:
    executor:
      name: node/default
      tag: "lts"
    steps:
      - checkout
      - node/install-packages: # Install and automatically cache packages
          override-ci-command: npm install
      - run: npm run build
      - run: node ./dist/index.js --help # Run the CLI to ensure it works, we had some test releases where this was broken during the esm migration
      - run: npm test
      - run: npx semantic-release

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - release:
          context: dopry-npm-packages
