import { PeriodType } from "../enum";

export type DataType = "date" | "numeric" | "string";

export interface ReportMetricValue {
  value: string[]; // The value of the metric
  "@_year": string; // The year of the metric
  "@_month": string; // The month of the metric
  "@_periodType": PeriodType; // The period type of the metric
  "@_autoGenerated": boolean; // Indicates whether the metric is auto-generated by the system.
}

export interface IPropertyMetric {
  monthlyMetric?: ReportMetricValue[]; // the value of the monthly metric
  value?: string; // The value of the Non-Monthly metric
  "@_name": string; // The name of the metric
  "@_id": number; // The id of the metric
  "@_uom": string; // The unit of measure of the metric
  "@_dataType": DataType; // The data type of the value the metric (i.e., string, numeric, date).
  "@_autoGenerated": boolean; // Indicates whether the metric is auto-generated by the system.
}

export interface PropertyMetrics {
  "@_year": number;
  "@_month": number;
  "@_periodType": PeriodType;
  "@_propertyId": number;

  metric: IPropertyMetric[];
}
